apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackprog-app
  namespace: fullstackprog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstackprog-app
  template:
    metadata:
      labels:
        app: fullstackprog-app
    spec:
      containers:
        - name: fullstackprog-app
          image: ghcr.io/cl-krma/fullstackprog-app:685e3801191bdd5dbf31dfcfdcbadedc2c879c0d
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: db
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: pass
            - name: DB_NAME
              value: myapp
            - name: JWT_SECRET
              value: secretKey
---
apiVersion: v1
kind: Service
metadata:
  name: fullstackprog-app-service
  namespace: fullstackprog
spec:
  selector:
    app: fullstackprog-app
  ports:
    - port: 80
      targetPort: 3000
